apiVersion: apps/v1
kind: Deployment
metadata:
  name: automotive-deployment

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: automotive

  template:
    metadata:
      labels:
        app: automotive

    spec:
      containers:
      - name: automotive
        image: automotive-api:v1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000
